//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUB_EmpleadosDeptos.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_DEPARTAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEPARTAMENTO()
        {
            this.TBL_EMPLEADO = new HashSet<TBL_EMPLEADO>();
        }
    
        public int Codigo { get; set; }
        [Required(ErrorMessage = "El Nombre del Departamento es Obligatorio")]
        [MinLength(5, ErrorMessage = "El Nombre del Departamento debe Tener al Menos 5 Caracteres")]
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EMPLEADO> TBL_EMPLEADO { get; set; }
    }
}
