//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUB_EmpleadosDeptos.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_EMPLEADO
    {
        public int Codigo { get; set; }
        [Required(ErrorMessage = "El Nombre es Obligatorio")]
        [MinLength(3, ErrorMessage = "El Nombre debe Tener al Menos 3 Caracteres")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "La Cédula es Obligatoria")]
        [RegularExpression("^[0-9]{11}$", ErrorMessage = "Son 11 Digitos")]
        //^[0-9]{1,12}$
        //@" ^ (\d{11})$
        public string Cedula { get; set; }
        [Required(ErrorMessage = "El Cargo es Obligatorio")]
        [MinLength(5, ErrorMessage = "El Cargo Debe Tener 5 Caracteres Mínimo")]
        public string Cargo { get; set; }
        public int Departamento { get; set; }
        [Required(ErrorMessage = "El Sueldo es Obligatorio")]
        [Range(0,500000,ErrorMessage ="El Sueldo Es Muy Elevado")]
        [RegularExpression("$?([0-9]+)(.[0-9][0-9])?$", ErrorMessage = "Valor de Sueldo Incorrecto")]
        public Nullable<decimal> Sueldo { get; set; }
        public virtual TBL_DEPARTAMENTO TBL_DEPARTAMENTO { get; set; }
    }
}
